### ISSUE TITLE
Placeholder for "Rate" is not visible in "Add your today's Wins" modal

### ISSUE THREAD

**Issue by FrozenHearth** [sonigeez/Memento#4]
"Rate it between 1-10" is the placeholder which isn't visible:

<img width="1728" alt="Screenshot 2023-08-03 at 11 55 40 PM" src="https://github.com/sonigeez/Memento/assets/27160715/0274166e-88d4-483c-b52a-f3ef272cf89d">

Allow an empty input and disable the Save button if the input is empty. This way the placeholder is visible.

**Comment by sonigeez** [comment]
thanks @FrozenHearth for mentioning this issue
